### ISSUE TITLE
"#AccessibleOlli" not "Accessible Olli"

### ISSUE THREAD

**Issue by joespeed** [AccessibleOlli/olli-stop#13]
change to "#AccessibleOlli" instead of "AccessibleOlli". "#AccessibleOlli" is the actual name.

Should say or not say "Copyright IBM" here?

![image](https://user-images.githubusercontent.com/8238588/34172990-d7e67b9a-e4c1-11e7-937c-f90d3f8701d8.png)

**Comment by isc-rsingh** [comment]
@joespeed bigger question is do you like this attribution at all? I just threw it in there for discussion
